image:
  repository: cr.yandex/crp8pmpt39t70k7ra3uf/gateway
service:
  port: 8080
env:
  - name: ServiceUrls__LibraryServiceUrl
    value: "http://library:8080"
  - name: ServiceUrls__RatingServiceUrl
    value: "http://rating:8080"
  - name: ServiceUrls__ReservationServiceUrl
    value: "http://reservation:8080"
ingress:
  enabled: true
  className: "nginx"
  host: ""
  path: "/"
  pathType: "Prefix"