image:
  repository: cr.yandex/crp8pmpt39t70k7ra3uf/rating
  tag: "latest"
service:
  port: 8080
env:
  - name: ConnectionStrings__Postgres
    valueFrom:
      secretKeyRef:
        name: db-connection-strings
        key: rating-connection